// <auto-generated />
using HarshitCommunications.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarshitCommunications.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250125124816_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HarshitCommunications.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Charger"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Cables"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Air Buds"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Neck Band"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Car Charger"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Power Bank"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Smart Watch"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Speakers"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Earphone"
                        });
                });

            modelBuilder.Entity("HarshitCommunications.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "{\r\n                        \"Bluetooth Version\": \"5.1+EDR\",\r\n                        \"Music Time\": \"25 Hours in Total\",\r\n                        \"Earphone Battery Capacity\": \"26 mAh\",\r\n                        \"Earphone Talk Time\": \"4hr\",\r\n                        \"Earphone Charging Time\": \"1.5hr\",\r\n                        \"Speaker Size\": \"13mm\",\r\n                        \"Charging Case Battery Capacity\": \"300 mAh\",\r\n                        \"Charging Case Time\": \"2Hr\",\r\n                        \"Standby Time\": \"500 Hours\",\r\n                        \"Distance\": \"10M\"\r\n                    }",
                            Name = "COOLPODS 9",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "{\r\n                        \"Bluetooth Version\": \"5.1+EDR\",\r\n                        \"Music Time\": \"40 Hours in Total\",\r\n                        \"Earphone Battery Capacity\": \"30 mAh\",\r\n                        \"Earphone Talk Time\": \"5hr\",\r\n                        \"Earphone Charging Time\": \"1.5hr\",\r\n                        \"Speaker Size\": \"8mm\",\r\n                        \"Charging Case Battery Capacity\": \"270 mAh\",\r\n                        \"Charging Case Time\": \"2Hr\",\r\n                        \"Standby Time\": \"500 Hours\",\r\n                        \"Distance\": \"10M\"\r\n                    }",
                            Name = "COOLPODS 12",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "{\r\n                        \"Wireless Version\": \"5.0\",\r\n                        \"Talk Time\": \"40 Hours\",\r\n                        \"Music Time\": \"36 Hours\",\r\n                        \"Stand By Time\": \"400 Hours\",\r\n                        \"Charging Time\": \"2 Hours\",\r\n                        \"Charging Type\": \"Type-C\",\r\n                        \"Battery Capacity\": \"250mAh\",\r\n                        \"Transmission Distance\": \"10M\",\r\n                        \"Speaker Size\": \"10MM\"\r\n                    }",
                            Name = "ROVER 3",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "{\r\n                        \"Wireless Version\": \"5.0\",\r\n                        \"Talk Time\": \"35 Hours\",\r\n                        \"Music Time\": \"30 Hours\",\r\n                        \"Stand By Time\": \"400 Hours\",\r\n                        \"Charging Time\": \"2 Hours\",\r\n                        \"Charging Type\": \"Micro USB\",\r\n                        \"Battery Capacity\": \"250mAh\",\r\n                        \"Transmission Distance\": \"10M\",\r\n                        \"Speaker Size\": \"10MM\"\r\n                    }",
                            Name = "ROVER 5",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "{\r\n                        \"Model\": \"HYDRO 2\",\r\n                        \"Bluetooth Version\": \"5.0\",\r\n                        \"Standby Time\": \"Up to 150 Hours\",\r\n                        \"Talk Time\": \"28 Hours\",\r\n                        \"Music Time\": \"20 Hours\",\r\n                        \"Charging Time\": \"2 Hours\",\r\n                        \"Battery Capacity\": \"400mAh\",\r\n                        \"Speaker Size\": \"40MM\",\r\n                        \"Use Distance\": \"Up to 10mm\"\r\n                    }",
                            Name = "HYDRO 2",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 6,
                            Description = "{\r\n                        \"Model\": \"HYDRO 3\",\r\n                        \"Bluetooth Version\": \"5.3+EDR\",\r\n                        \"Standby Time\": \"Up to 150 Hours\",\r\n                        \"Talk Time\": \"25 Hours\",\r\n                        \"Music Time\": \"20 Hours\",\r\n                        \"Charging Time\": \"2 Hours\",\r\n                        \"Battery Capacity\": \"200mAh\",\r\n                        \"Speaker Size\": \"40MM\",\r\n                        \"Use Distance\": \"Up to 10mm\"\r\n                    }",
                            Name = "HYDRO 3",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 7,
                            Description = "{\r\n                        \"Battery\": \"Polymer Li-on Battery\",\r\n                        \"Battery Capacity=\": \"10000mAh\",\r\n                        \"Input Ports\": \"Micro USB, Type-C\",\r\n                        \"Output Ports\": \"USB-A\",\r\n                        \"Portable Cable\": \"Lightning, Type-C, Micro USB\",\r\n                        \"Material\": \"PC+ABS\"\r\n                    }",
                            Name = "POWERBOX 5",
                            Price = 3999.0
                        },
                        new
                        {
                            Id = 8,
                            Description = "{\r\n                        \"Battery\": \"Polymer Li-on Battery\",\r\n                        \"Battery Capacity=\": \"10000mAh\",\r\n                        \"Input Ports\": \"USB-A, Type-C\",\r\n                        \"Output Ports\": \"USB-A\",\r\n                        \"Portable Cable\": \"Lightning, Type-C, Micro, USB-A\",\r\n                        \"Material\": \"PC+ABS\"\r\n                    }",
                            Name = "POWERBOX 8",
                            Price = 4999.0
                        },
                        new
                        {
                            Id = 9,
                            Description = "{\r\n                        \"Model\": \"Lancer 2\",\r\n                        \"Screen Size\": \"2.0 inch\",\r\n                        \"Charging Mode\": \"Wireless Charger\",\r\n                        \"Battery Backup\": \"3-4 Days with BT\",\r\n                        \"Application\": \"FereFit\",\r\n                        \"Bluetooth Calling\": \"Yes\",\r\n                        \"AI Voice Assistant\": \"Yes\",\r\n                        \"Waterproof Level\": \"IP67\",\r\n                        \"BT Version\": \"3.0/5.0\"\r\n                    }",
                            Name = "Lancer 2",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 10,
                            Description = "{\r\n                        \"Model\": \"Lancer 3\",\r\n                        \"Screen Size\": \"2.0 inch\",\r\n                        \"Charging Mode\": \"Magnet Charge\",\r\n                        \"Battery Backup\": \"3-4 Days\",\r\n                        \"Application\": \"HryFine\",\r\n                        \"Bluetooth Calling\": \"Yes\",\r\n                        \"AI Voice Assistant\": \"Yes\",\r\n                        \"Waterproof Level\": \"IP67\",\r\n                        \"BT Version\": \"3.0/5.0\"\r\n                    }",
                            Name = "Lancer 3",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 11,
                            Description = "{\r\n                        \"Output\": \"22W MAX\",\r\n                        \"Ports\": \"Type-C\",\r\n                        \"Protocols Supported\": \"QC3.0, PD, VOOC\",\r\n                        \"Fast Charging Supported\": \"Samsung OPPO, ONE+, VIVO, REALME, MI\"\r\n                    }",
                            Name = "Chamber 4c",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 12,
                            Description = "{\r\n                        \"Output\": \"22W MAX\",\r\n                        \"Ports\": \"Type-C\",\r\n                        \"Protocols Supported\": \"QC3.0, PD, VOOC\",\r\n                        \"Fast Charging Supported\": \"Samsung OPPO, ONE+, VIVO, REALME, MI\"\r\n                    }",
                            Name = "Chamber 4i",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 13,
                            Description = "{\r\n                        \"Current\": \"4A Output\",\r\n                        \"Wire Material\": \"Braided\",\r\n                        \"Length\": \"1 Meter\",\r\n                        \"Shell\": \"TPE\",\r\n                        \"Core\": \"Tinned Copper Wire\",\r\n                        \"Color\": \"Black & Grey\"\r\n                    }",
                            Name = "Flexy 3",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 14,
                            Description = "{\r\n                        \"Current\": \"4A Output\",\r\n                        \"Wire Material\": \"Braided\",\r\n                        \"Length\": \"1 Meter\",\r\n                        \"Shell\": \"Alluminium Alloy + TPE\",\r\n                        \"Core\": \"Tinned Copper Wire\",\r\n                        \"Color\": \"Black, Brown, Grey\"\r\n                    }",
                            Name = "Flexy 6",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 15,
                            Description = "{\r\n                        \"Driver Unit\": \"10mm\",\r\n                        \"Connector\": \"3.5mm audio jack\",\r\n                        \"Cord Length\": \"1.2m\"\r\n                    }",
                            Name = "Photon 4",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 16,
                            Description = "{\r\n                        \"Driver Unit\": \"10mm\",\r\n                        \"Connector\": \"3.5mm audio jack\",\r\n                        \"Cord Length\": \"1.2m\"\r\n                    }",
                            Name = "Photon 5",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 17,
                            Description = "{\r\n                        \"Model Name\": \"Piston 5L\",\r\n                        \"Input\": \"DC 12-24V\",\r\n                        \"Output\": \"5V = 2.4A (Max)\",\r\n                        \"Material\": \"ABS+PC\"\r\n                    }",
                            Name = "Piston 5L (Without Cable)",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 18,
                            Description = "{\r\n                        \"Model Name\": \"Piston 5L\",\r\n                        \"Input\": \"DC 12-24V\",\r\n                        \"Output\": \"DC5V/3.0A\",\r\n                        \"Port\": \"USB-A Port *2\"\r\n                    }",
                            Name = "Piston 7",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 19,
                            Description = "{\r\n                        \"Input Power\": \"5V = 1A\",\r\n                        \"Output\": \"10W(RWS)\",\r\n                        \"BT Version\": \"5.0\",\r\n                        \"Battery\": \"3.7V(1200mAh)\",\r\n                        \"Connectivity Options\": \"Wireless\",\r\n                        \"Dimensions\": \"64mm x 380mm x 56mm\"\r\n                    }",
                            Name = "JUKEBOX 3",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 20,
                            Description = "{\r\n                        \"Input Power\": \"5V = 1A\",\r\n                        \"Output\": \"20W(RWS)\",\r\n                        \"BT Version\": \"5.0\",\r\n                        \"Battery\": \"3.7V(3000mAh)\",\r\n                        \"Connectivity Options\": \"Wireless\",\r\n                        \"Dimensions\": \"212mm x 367mm x 158mm\"\r\n                    }",
                            Name = "JUKEBOX 4",
                            Price = 3299.0
                        },
                        new
                        {
                            Id = 21,
                            Description = "{\r\n                        \"Cable Length\": \"1 meter\",\r\n                        \"Material\": \"Braided wire\",\r\n                        \"Color\": \"Black with Silver Alloy\",\r\n                        \"Interface\": \"Type-C to 3.5mm Aux\",\r\n                        \"Input\": \"USB Type-C\",\r\n                        \"Output\": \"3.5mm Aux\"\r\n                    }",
                            Name = "Flame 1t",
                            Price = 3299.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
