// <auto-generated />
using HarshitCommunications.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarshitCommunications.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HarshitCommunications.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Charger"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Cables"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Air Buds"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Neck Band"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Car Charger"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Power Bank"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Smart Watch"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Speakers"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Earphone "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
